version: '2.1'
services:

  postgres:
    image: postgres:14.8-alpine3.18
    environment:
      POSTGRES_DB: "jreport"
      POSTGRES_USER: "stud"
      POSTGRES_PASSWORD: "stud"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - habrdb-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - robonet

  mongo:
    image: mongo:5.0
    container_name: mongo-1
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_DATABASE=jreport
      #- MONGO_INITDB_ROOT_USERNAME=admin
      #- MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      # seeding scripts
      - ./mongo-entrypoint:/docker-entrypoint-initdb.d
      # named volumes
      - mongodb:/data/db
      - mongoconfig:/data/configdb
    networks:
      - robonet

  robot:
    build: 
      context: robot
    container_name: robot
    restart: always
    environment:
      - DATABASE_IP=postgres
      - DATABASE_PORT=5432
      - DATABASE_LOGIN=stud
      - DATABASE_PASSWORD=stud
      - DATABASE_NAME=jreport
      - JIRA_ADDRESS=https://jira.mts.ru
      - MONGO_ADDRESS=mongo-1
      - MONGO_PORT=27017
      - JIRA_USER=
      - JIRA_PASSWORD=
      - CONFLUENCE_USER=
      - CONFLUENCE_PASSWORD=
      - CONFLUENCE_ADDRESS=https://confluence.mts.ru/rest/api
      - INIT_SQL=database_init.json
    volumes:
      - /home/stud/jreport/database_init.sql:/jreport/database_init.sql
    depends_on:
      - mongo
      - postgres
    networks:
      - robonet


networks:
    robonet:

volumes:
  mongodb:
  mongoconfig:
  habrdb-data:
