version: '2.1'
services:
  db-node:
    build:
      context: mysql
      dockerfile: Dockerfile
    container_name: db-node
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: jreport
      MYSQL_USER: stud
      MYSQL_PASSWORD: stud
      MYSQL_ROOT_PASSWORD: '1'
    command: >
      --sql-mode='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
      --general-log=ON
      --log-queries-not-using-indexes=ON
    ports:
      - 3360:3306
    volumes:
      - db-node-data:/var/lib/mysql
    networks:
      - robonet
      
  mongo:
    image: mongo:5.0
    container_name: mongo-1
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_DATABASE=jreport
      #- MONGO_INITDB_ROOT_USERNAME=admin
      #- MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      # seeding scripts
      - ./mongo-entrypoint:/docker-entrypoint-initdb.d
      # named volumes
      - mongodb:/data/db
      - mongoconfig:/data/configdb
    networks:
      - robonet

  robot:
    build: 
      context: robot
    container_name: robot
    environment:
      - DATABASE_IP=db-node
      - DATABASE_PORT=3306
      - DATABASE_LOGIN=stud
      - DATABASE_PASSWORD=stud
      - DATABASE_NAME=jreport
      - JIRA_ADDRESS=https://jira.mts.ru
      - MONGO_ADDRESS=mongo-1
      - MONGO_PORT=27017
      - JIRA_USER=dvdzyub1
      - JIRA_PASSWORD=3.14Oneer4
      - CONFLUENCE_USER=dvdzyub1
      - CONFLUENCE_PASSWORD=3.14Oneer4
      - CONFLUENCE_ADDRESS=https://confluence.mts.ru/rest/api
    depends_on:
      - mongo
      - db-node
    networks:
      - robonet


networks:
    robonet:

volumes:
  mongodb:
  mongoconfig:
  db-node-data:
